[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[serversTransport]
  insecureSkipVerify = true
  maxIdleConnsPerHost = 0

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
  [entryPoints.traefik]
    address = ":8080"

[providers]
  providersThrottleDuration = "2s"
  [providers.kubernetesIngress]
    throttleDuration = "0s"
    [providers.kubernetesIngress.ingressEndpoint]
      publishedService = "kubeaddons/traefik-kubeaddons"

[api]
  insecure = true
  dashboard = true

[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"

[ping]
  entryPoint = "http"

[log]
  level = "info"
  format = "json"
